name: GatorGrader

on:
  push:
    branches: [main]

jobs: 
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'
    - name: Setup Python
      if: always()
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.10.6
    - name: Set up grading environment
      run: |
        sudo apt-get update
        sudo python -m pip install --upgrade pip
        sudo python -m pip install gatorgrade --ignore-installed PyYAML
    - name: Grade repository
      run: |
        gatorgrade --config .gatorgrade.yml
      if: always()
      env:   
        PIPENV_VENV_IN_PROJECT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1
    - name: Create Wizard report
      id: wizard
      uses: term-world/wizard@v0.5.4
      with:
        gatorgrade-config: '.gatorgrade.yml'
      if: always()
    env:
      GITHUB_TOKEN: ${{ secrets.ARBORIST }}
